### ISSUE TITLE
Course Status displayed on public site

### ISSUE THREAD

**Issue by tobiasbork** [corona-school/web-user-app#83]
Currently, for one of the courses it looks like the course status is displayed publicly. This should be looked into and removed.
![image](https://user-images.githubusercontent.com/39235832/94370358-de32ff80-00ef-11eb-9321-bf63fab5c9b5.png)

**Comment by geroembser** [comment]
Okay, I have tried to find out what the problem is. Is it possible that someone was logged in as the "If-Clauses English" course's instructor while capturing the screenshot? In this case, it will display the "Erlaubt" label, but it shouldn't appear for all others (including the public if someone is not logged in at all). So if this is possible, we know the problem and we can fix it. But this doesn't look like a bigger problem.

**Comment by tobiasbork** [comment]
Yes, you are right. This is only displayed if I am the instructor of the course. Hence, this is a minor problem that does not need fixing necessarily.

**Comment by lsc0498** [comment]
This was solved in commit [`36b682a4`](https://github.com/corona-school/web-user-app/commit/36b682a456c8fa23644159cb215655821cb74dc9)
